from enum import Enum

class Constant(Enum):
    RICH_LINE = 5000
    MIDDLE_LINE = 2000
    POOR_LINE = 500

    RICH_SPEND = 600
    MIDDLE_SPEND_MORE = 500
    MIDDLE_SPEND_LESS = 400
    MIDDLE_SPEND_IDLE = 300
    POOR_SPEND_MORE = 300
    POOR_SPEND_LESS = 200
    POOR_SPEND_IDLE = 100

    RICH_QUOTA = 2
    MIDDLE_QUOTA = 3
    POOR_QUOTA = 5

    MIDDLE_CONTRIBUTE_MORE = 800
    MIDDLE_CONTRIBUTE_LESS = 400
    POOR_CONTRIBUTE_MORE = 400
    POOR_CONTRIBUTE_LESS = 200

    # Rich:Middle:Poor = 5:3:2
    RICH_REMAINING_PROPORTION = 0.5 # Rich get 50% MAX (5:3+2)
    MIDDLE_REMAINING_PROPORTION = 0.6 # For remaining Middle get 60% MAX (3:2)
    POOR_REMAINING_PROPORTION = 1 # For remaining Poor get 100% MAX

